### ISSUE TITLE
Error: Can't resolve `reportWebVitals`

### ISSUE THREAD

**Issue by recursivecodes** [aws-samples/amazon-ivs-bullet-chat-web-demo#4]
When running this demo, the following error is thrown:

![2023-09-20_16-57-27](https://github.com/aws-samples/amazon-ivs-bullet-chat-web-demo/assets/41924046/02f03f82-31cd-472c-90ab-3ce327546bdf)

Seems like this file is missing from the repository.

**Comment by slee-aws** [comment]
Sorry you experienced this issue @recursivecodes! A fix has been merged into main.
